#include "juce_organicui.h"

#include "comment/Comment.cpp"
#include "comment/CommentManager.cpp"
#include "comment/ui/CommentUI.cpp"
#include "comment/ui/CommentManagerViewUI.cpp"

#include "dashboard/Dashboard.cpp"
#include "dashboard/DashboardItem.cpp"
#include "dashboard/DashboardCommentItem.cpp"
#include "dashboard/DashboardGroupItem.cpp"
#include "dashboard/DashboardItemFactory.cpp" 
#include "dashboard/DashboardItemManager.cpp"
#include "dashboard/DashboardManager.cpp"
#include "dashboard/ui/DashboardItemManagerUI.cpp"
#include "dashboard/ui/DashboardItemUI.cpp"
#include "dashboard/ui/DashboardCommentItemUI.cpp"
#include "dashboard/ui/DashboardGroupItemUI.cpp"
#include "dashboard/ui/DashboardManagerUI.cpp"
#include "dashboard/ui/DashboardManagerView.cpp"
#include "dashboard/ui/DashboardUI.cpp"


#include "inspectable/dashboard/DashboardInspectableItem.cpp"
#include "controllable/dashboard/DashboardControllableItem.cpp"
#include "controllable/dashboard/DashboardTriggerItem.cpp"
#include "controllable/dashboard/DashboardCCItem.cpp"
#include "inspectable/dashboard/ui/DashboardInspectableItemUI.cpp"
#include "controllable/dashboard/ui/DashboardControllableItemUI.cpp"
#include "controllable/dashboard/ui/DashboardTriggerItemUI.cpp"
#include "controllable/dashboard/ui/DashboardCCItemUI.cpp"
#include "controllable/parameter/dashboard/DashboardParameterItem.cpp"
#include "controllable/parameter/dashboard/ui/DashboardParameterItemUI.cpp"